# Step 1: Build the Angular application using Node.js
FROM node:14 as build

# Set the working directory inside the container
WORKDIR /app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli@12

# Copy the package.json and package-lock.json files to install dependencies
COPY ./web/package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire Angular codebase to the container
COPY ./web ./

# Expose port 4200 for development
EXPOSE 4200

# Start development server using `npm start`
CMD ["npm", "start"]